### ISSUE TITLE
Seems to be a cp error/leftover in heading

### ISSUE THREAD

**Issue by s-hemer** [phytec/doc-bsp-yocto#253]
https://github.com/phytec/doc-bsp-yocto/blob/ae8601628278b0535b4e65d4d940c94b8ec0866b/source/yocto/kirkstone.rst?plain=1#L1508

**Comment by jonas-rem** [comment]
@s-hemer can you directly open a PR that fixes this headline?

**Comment by s-hemer** [comment]
Will do, was just a reminder for myself.

**Comment by s-hemer** [comment]
Only thing: this also affects 
https://github.com/phytec/doc-bsp-yocto/blob/ae8601628278b0535b4e65d4d940c94b8ec0866b/source/locale/zh_CN/LC_MESSAGES/yocto.po?plain=1#L1585-L1586
