### ISSUE TITLE
AM64x documentation for PD24.1.0 has can0 instead of mcan0

### ISSUE THREAD

**Issue by cbrown-phytec** [phytec/doc-bsp-yocto#265]
https://docs.phytec.com/projects/yocto-phycore-am64x/en/bsp-yocto-ampliphy-am64x-pd24.1.0/interfaceguides/can.html

The interface guide currently says to use the commands 
ip link set can0 down
ip link set can0 up type can bitrate 1000000
ip link set can0 up

Per SW, the new commands should be
ip link set mcan0 down
ip link set mcan0 up type can bitrate 1000000
ip link set mcan0 up

Presumably this also needs to be changed anywhere else in the documentation that references can0 or can1

**Comment by jonas-rem** [comment]
The documentation for the am64x is not hosted in this repository so far. I think this issue rather belongs to the repository `https://github.com/phytec/docs`. Let me know if you have plans to integrate or link it in this repo.

**Comment by cbrown-phytec** [comment]
Thank you for the quick response. I think you are correct about this being the incorrect repository. I will move the issue to the correct one.
